In [10]:
%%time
import time
def Multiply(A,B):
    result=[ [0,0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0,0] ]
    #for rows
    for i in range(len(A)):
        #for columns
        for j in range(len(B[0])):
            #for rows of matrix B
            for k in range(len(B)):
                result[i][j] += A[i][k] * B[k][j]

    for p in result:
        print(p)

    return 0

A = [ [1, 2, 3,4,5,6,7,8,9,10],[1, 2, 3,4,5,6,7,8,9,10], [1, 2, 3,4,5,6,7,8,9,10] ]
  
B = [[1, 2, 3,4,5,6,7,8,9,10],[1, 2, 3,4,5,6,7,8,9,10], [1, 2, 3,4,5,6,7,8,9,10] ]

#print("Result: ")
#s=time.clock()
Multiply(A,B)
#e=time.clock()
#print("--- %0.10f seconds ---" % (e - s))


[6, 12, 18, 24, 30, 36, 42, 48, 54, 60]
[6, 12, 18, 24, 30, 36, 42, 48, 54, 60]
[6, 12, 18, 24, 30, 36, 42, 48, 54, 60]
Wall time: 0 ns


0

In [11]:
%%time
import numpy as np

A = [[12, 7, 3], [4, 5, 6], [7, 8, 9]] 

B = [[5, 8, 1, 2], [6, 7, 3, 0], [4, 5, 9, 1]]

result= [[0,0,0,0], [0,0,0,0], [0,0,0,0]]

result= np.dot(A,B)

for p in result:
    print(p)

[114 160  60  27]
[74 97 73 14]
[119 157 112  23]
Wall time: 27.6 s
